[project]
name = "neocore"
version = "0.1.0"
channels = [
  "https://conda.modular.com/max-nightly",
  "conda-forge"
]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
python = "3.11.*"
pytest = "*"
