name: NeoCore CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}      # <- keeps Pixi PATH for every step
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v1
        with:
          cache: true

      - name: Install dependencies
        run: pixi install

      - name: Generate stub kernels
        run: |
          pixi run python scripts/gen_kernels.py \
            --max 1500                       # optional arg (see patch below)

      - name: Run tests (placeholder ok)
        run: |
          cd neocore
          pixi run pytest -q || echo "No tests yet"

      # Optional Mojo compilation—uncomment when kernels compile
      # - name: Build all Mojo kernels
      #   run: |
      #     find neocore/src/kernels -name '*.mojo' \
      #       | xargs -I{} mojo build {} --emit shared-lib -o neocore/build