name: NeoCore CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0
        with:
          cache: true

      - name: Resolve env
        run: pixi install

      - name: Generate kernels (≤1500)
        run: pixi run python scripts/gen_kernels.py --max 1500

      - name: Dummy test (always pass)
        run: echo "✓ build finished"