name: Build & Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      
      - name: Generate Mojo kernels
        run: python neocore/scripts/gen_kernels.py
      
      - name: Run Python tests
        run: |
          cd neocore
          python -m pytest tests/
      
      - name: Count generated kernels
        run: |
          echo "Total Mojo files generated:"
          find neocore/src/kernels -name "*.mojo" | wc -l
          
  # Mojo build job - will be enabled when Mojo is available on CI
  # mojo-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     
  #     - name: Install Modular and Mojo
  #       run: |
  #         curl -sSL https://get.modular.com | bash
  #         modular auth
  #         modular install mojo
  #     
  #     - name: Build Mojo kernels
  #       run: |
  #         export PATH=$HOME/.modular/bin:$PATH
  #         mkdir -p neocore/build
  #         find neocore/src/kernels -name "*.mojo" -type f | while read file; do
  #           echo "Building: $file"
  #           mojo build "$file" --no-optimization -o "neocore/build/$(basename $file .mojo).mojopkg" || true
  #         done