name: Build & Test
on: [push, pull_request]

jobs:
  neo-core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Install Pixi + Modular tool‑chain
      - uses: prefix-dev/setup-pixi@v0
      - run: pixi install

      # 2. Generate missing Mojo stubs from the CSV
      - run: pixi run python scripts/gen_kernels.py

      # 3. Run Python tests (or placeholder if none yet)
      - run: |
          cd neocore
          pixi run pytest -q || echo "no tests yet"

      # 4. Optional: build all Mojo kernels (uncomment later when it's stable)
      #- run: |
      #    find neocore/src/kernels -name '*.mojo' \
      #      | xargs -I{} mojo build {} --emit shared-lib -o neocore/build